# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"upstream_splitter": "01_learn.ipynb",
         "SSLLearner": "01_learn.ipynb",
         "DotProduct": "02_loss.ipynb",
         "NTXnetLoss": "02_loss.ipynb",
         "BaseSSLLoss": "02_loss.ipynb",
         "CGDLoss": "02_loss.ipynb",
         "CGDResNet": "03_models.ipynb",
         "arch_map": "03_models.ipynb",
         "rep_resnet": "03_models.ipynb",
         "L2Norm": "03_models.ipynb",
         "lin_layer": "03_models.ipynb",
         "BatchDropBlock": "03_models.ipynb",
         "RepresentationHead": "03_models.ipynb",
         "create_bottleneck": "03_models.ipynb",
         "SSLModel": "03_models.ipynb",
         "ImageRepEncoder": "03_models.ipynb",
         "SIMClrHead": "03_models.ipynb",
         "Encoding": "04_utils.ipynb",
         "make_encoder": "04_utils.ipynb",
         "DropLastBatchCallback": "04_utils.ipynb",
         "TensorSSLImage": "05_transforms.ipynb",
         "SSLImage": "05_transforms.ipynb",
         "SSLTransform": "05_transforms.ipynb"}

modules = ["learn.py",
           "loss.py",
           "models.py",
           "utils.py",
           "transforms.py"]

doc_url = "https://Samjoel3101.github.io/ssl_fastai2/"

git_url = "https://github.com/Samjoel3101/ssl_fastai2/tree/master/"

def custom_doc_links(name): return None
